name: ruby-setup

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Ruby
      uses: masa-iwasaki/setup-ruby@be1f409

    - name: Run 'bundle install'
      run: |
        bundle install
    