name: ruby-setup

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Ruby
      uses: masa-iwasaki/setup-ruby@e1a9bd158e61100e5d4e2e0fcd8468895d087b39

    - name: Run 'bundle install'
      run: |
        bundle install
    
    - name: Remove .ruby_versoin
      run: |
        rm .ruby_version

    - name: Set up Ruby without .ruby_version
      uses: masa-iwasaki/setup-ruby@e1a9bd158e61100e5d4e2e0fcd8468895d087b39

    - name: Run 'bundle install' again
      run: |
        bundle install
    