name: ruby-setup

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Ruby with "version" parameter
      uses: masa-iwasaki/setup-ruby@724667021bf41f7cfc303e935f4b1e81ab6b76dd
      with:
        version: 2.5.x

    - name: Remove .ruby-versoin
      run: |
        echo "2.6.x" > .ruby-version

    - name: Set up Ruby with .ruby-version
      uses: masa-iwasaki/setup-ruby@724667021bf41f7cfc303e935f4b1e81ab6b76dd
    